### ISSUE TITLE
bug report:

### ISSUE THREAD

**Issue by wenboown** [OpenBMB/IoA#11]
https://github.com/OpenBMB/IoA/blob/fe7059bb35c5776a90a2b463f2a0ed4814d5e956/im_client/agents/open_interpreter/open_interpreter_agent.py#L79-L81

This will make the `interpreter_instance` always be  "gpt-4-1106-preview" should be something like the following?

```
    interpreter_instance.model = "gpt-4-1106-preview"
    if task_desc.model != "":
        interpreter_instance.model = task_desc.model
```

or 
```
    if task_desc.model != "":
        interpreter_instance.model = task_desc.model
    else:
        interpreter_instance.model = "gpt-4-1106-preview"
```

**Comment by minleminzui** [comment]
thank you， I'll fix it。：-）
