### ISSUE TITLE
IEEE P2874

### ISSUE THREAD

**Issue by GadgetNutt** [OpenBMB/IoA#2]
IEEE P2874

**Comment by chenweize1998** [comment]
Hi, could you explain the issue in more detail?

**Comment by GadgetNutt** [comment]
https://sagroups.ieee.org/2874/

This standard describes a Hyperspace Transaction Protocol (HSTP) that enables interoperable, semantically compatible connections between connected hardware (e.g. autonomous drones, sensors, smart devices, robots) and software (e.g. services, platforms, applications, artificial intelligence systems).

**Comment by chenweize1998** [comment]
Cool. Any insights on how this standard could be used to enhance agent communication and collaboration? We are not that familiar with this standard actually.

**Comment by chenweize1998** [comment]
Thanks for pointing this out. We will take a look and keep our eyes on the standard. For now, we will close the issue. Feel free to reopen it if you have any ideas to contribute or suggestions to help integrate the standard :)
